language: objective-c
# xcode_project: ActionSheetPicker.xcodeproj # path to your xcodeproj folder
# xcode_scheme: ActionSheetPickerTests
# xcode_sdk: iphonesimulator

script:
  - xctool clean build test -project ActionSheetPicker.xcodeproj -scheme ActionSheetPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=7.0'