language: objective-c
osx_image: xcode9.1
# before_install:
    # - brew update
    # - brew install xctool
script:
    - xcodebuild clean build test -workspace ActionSheetPicker-3.0.xcworkspace -scheme ActionSheetPicker -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.0,name=iPhone X" ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    recipients:
      - sky4winder+actionSheetPicker@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
